name: Debug
on:
  status
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: debug
        uses: hmarr/debug-action@v2
      - run: echo "Success!"
        if: github.event.context === 'deploy/netlify' && github.event.state == 'success'
