name: Debug
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for status checks'
          id: waitforstatuschecks
          uses: "WyriHaximus/github-action-wait-for-status@v2"
          with:
            ignoreActions: automerge
            checkInterval: 13
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: hmarr/debug-action@v2